services:
  app:
    build:
      context: .
    image: stack-base-go:local
    ports:
      - "8080:8080"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
